version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rt53-take1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nl1y3wyeui7w"
s3_prefix = "rt53-take1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MaliciousDomainsS3Bucket=\"tmak-rt53-resolver-logs\" MaliciousDomainsS3KeyName=\"config/all-malicious-domains.txt\" DDBTableName=\"malicious-domains\" NotifyInvalid=\"NotifyInvalid\" S3BucketNameForRT53Logs=\"rt53-resolver-query-logs\""

