version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rt53-take3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nl1y3wyeui7w"
s3_prefix = "rt53-take3"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MaliciousDomainsS3Bucket=\"tmak-rt53-resolver-logs\" MaliciousDomainsS3KeyName=\"config/all-malicious-domains.txt\" DDBTableName=\"domains2\" Rt53LogsSNSTopicName=\"tarik-sns-topic\" NotifyInvalid=\"y\" S3BucketNameForRT53Logs=\"tarik-rt53-logs\""

