AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for Route 53 Resolver DNS Query log processing
Parameters: 
  DDBInterestingDomainsTable:
    Description: DynamoDB Table to store list of interesting domains
    Default: interesting-domains-table
    Type: String
  DDBTableRCU:
    Description: DynamoDB Table Read Capacity Units 
    Type: Number
    Default: 50
  DDBTableWCU:
    Description: DynamoDB Table Write Capacity Units 
    Type: Number
    Default: 50
  S3InterestingDomainsBucketName:
    Description: Name for the S3 bucket where you plan to deposit interesting domains file
    Type: String
    Default: interesting-domains-bucket
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  S3DNSLogsBucketName:
    Description: Name for the S3 bucket for DNS Query Logs output
    Type: String
    Default: dns-logs-output
    MinLength: 3
    MaxLength: 63
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  StreamProcessorMemorySize:
    Description: Memmory allocation for Stream Processing Lambda Function
    Default: 256
    Type: Number
  StreamProcessorTimeout:
    Description: Timeout for Stream Processing Lambda Function
    Default: 120
    Type: Number
  StreamOutput3Prefix:
    Type: String
    Default: dns-query-logs/!{timestamp:yyyy/MM/dd}
    Description: S3 prefix for Kinesis output
  StreamOutputErrorPrefix:
    Type: String
    Default: dns-query-logs/!{timestamp:yyyy/MM/dd}
    Description: S3 prefix for Kinesis output
    Default: delivery-failures/!{firehose:error-output-type}/!{timestamp:yyyy/MM/dd}
  StreamOutputCompressionFormat:
    Description: Compression that Firehose will use to output logs to S3
    Type: String
    Default: GZIP
    AllowedValues: [GZIP]
  StreamBufferingInterval:
    Description: Amount of time that Firehose will wait to output logs to S3
    Type: Number
    Default: 60
    MinValue: 60
    MaxValue: 900
  StreamBufferSize:
    Description: Amount of logs data that Firehose will buffer before outputting 
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 128
  SNStopicName:
    Description: Name for the SNS topic to receive notifications
    Type: String
    Default: dns-logs-match-topic
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
  SNSinUse:
    Type: String
    Default: 'Y'
    AllowedValues:
    - 'Y'
    - 'N'
    Description: Confirm if you want to receive SNS notification when matches are found. You will still need to subscribe to the topic.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
Resources:
  # DynamoDB table to store list of interesting domains
  InterestingDomainsDynamoDBTable: 
    Type: AWS::Serverless::SimpleTable
    Properties: 
      TableName: !Ref DDBInterestingDomainsTable
      PrimaryKey: 
        Name: domainName
        Type: String
      ProvisionedThroughput: 
        ReadCapacityUnits: !Ref DDBTableRCU
        WriteCapacityUnits: !Ref DDBTableWCU
  # S3 Bucket for storing list of interesting domains as well as for FH to store the logs
  DNSLogsDeliveryBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref S3DNSLogsBucketName
  S3InterestingDomainsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Ref S3InterestingDomainsBucketName

  # SNS Topic to receive notification when matches are found
  AlertOnMatchSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SNStopicName

  # Lambda Function that will be invoked by Firehose and in turn will check if queried domain is interesting
  StreamInlineProcessingFunction:
    Type: AWS::Serverless::Function
    FunctionName: RT53-KinesisStreamDNSLogsProcessor
    Properties:
      CodeUri: stream_processor/
      Handler: stream_processor.lambda_handler
      Runtime: python3.8
      Timeout: !Ref StreamProcessorTimeout
      MemorySize: !Ref StreamProcessorMemorySize
      Environment:
        Variables:
          INTERESTING_DOMAINS_TABLE: !Ref DDBInterestingDomainsTable
          SNS_TOPIC: !Ref AlertOnMatchSNSTopic
          SNS_ON: !Ref SNSinUse
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref DDBInterestingDomainsTable
      - SNSPublishMessagePolicy:
          TopicName: !Ref SNStopicName
      
  
  DeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    DependsOn:
      - DNSLogsFirehosePolicy
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN: !Sub 'arn:aws:s3:::${DNSLogsDeliveryBucket}'
        BufferingHints:
          IntervalInSeconds: !Ref StreamBufferingInterval
          SizeInMBs: 50
        CompressionFormat: !Ref StreamOutputCompressionFormat
        Prefix: !Ref StreamOutput3Prefix
        ErrorOutputPrefix: !Ref StreamOutputErrorPrefix
        RoleARN: !GetAtt DNSLogsFirehoseRole.Arn
        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Parameters:
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt StreamInlineProcessingFunction.Arn 
              Type: Lambda   
  
  
  DNSLogsFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref 'AWS::AccountId'

  DNSLogsFirehosePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref DNSLogsFirehoseRole
      PolicyName: firehose_delivery_policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:AbortMultipartUpload'
              - 's3:GetBucketLocation'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:ListBucketMultipartUploads'
              - 's3:PutObject'
            Resource:
              - !GetAtt DNSLogsDeliveryBucket.Arn
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref DNSLogsDeliveryBucket
                  - '*'
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
              - 'lambda:GetFunctionConfiguration'
            Resource:
              - !GetAtt StreamInlineProcessingFunction.Arn
  

  # Function to import list of interesting domains and store them in DynamoDB table 
  ImportInterestingDomainsListFunc:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    FunctionName: RT53-InterestingDomainsImporter
    Properties:
      CodeUri: import_interesting_domains/
      Handler: import_interesting_domains.lambda_handler
      Runtime: python3.8
      Environment:
        Variables:
          INTERESTING_DOMAINS_TABLE: !Ref DDBInterestingDomainsTable
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref DDBInterestingDomainsTable
      - S3ReadPolicy:
          BucketName: !Ref S3InterestingDomainsBucketName
      Events:
        InterestingDomainsFileUpload:
          Type: S3
          Properties:
            Bucket: !Ref S3InterestingDomainsBucket
            Events: s3:ObjectCreated:*


 
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  
  ImportInterestingDomainsListFunctionOutput:
    Description: "ImportInterestingDomainsListFunc Lambda Function ARN"
    Value: !GetAtt ImportInterestingDomainsListFunc.Arn
  StreamInlineProcessingFunctionOutput:
    Description: "Lambda Function used by Firehose to check if domains are interesting or not"
    Value: !GetAtt StreamInlineProcessingFunction.Arn
  KinesisFirehosestreamARNOutput:
    Description: "Kinesis Firehose Delivery Stream for DNS Logs"
    Value: !GetAtt DeliveryStream.Arn
  DynamoDBTableOutput:
    Description: "DynamoDB table for maintaining list of interesting domains"
    Value: !Ref InterestingDomainsDynamoDBTable
  S3BucketDNSLogsOutput:
    Description: "S3 Bucket where DNS Logs are stored"
    Value: !Ref DNSLogsDeliveryBucket
  S3InterestingDomainsBucketOutput:
    Description: "S3 Bucket that will be storing interesting list of domains"
    Value: !Ref S3InterestingDomainsBucket
  AlertOnMatchSNSTopicARNOutput:
    Description: "ARN of the SNS Topic that can be notified on matched queries"
    Value: !Ref AlertOnMatchSNSTopic
  
  